version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: amar-assist-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - amar-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1

  webserver:
    image: nginx:stable
    container_name: amar-assist-webserver
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - amar-network

  mysql:
    image: mysql:8.0
    container_name: amar-assist-mysql
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amarassist
      MYSQL_USER: amar
      MYSQL_PASSWORD: assist
    volumes:
      - ./mysql-data:/var/lib/mysql
#    networks:
#      - amar-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  dbdata:

networks:
  amar-network:
    driver: bridge
